### ISSUE TITLE
Notice from Airtable to update Airtable JavaScript library

### ISSUE THREAD

**Issue by rgesulfo** [jbolda/gatsby-source-airtable#105]
Would it be possible to update to the latest version the Airtable package please?
It looks like there is a vulnerability in the previous one.
Thanks a lot! :)

Screenshot of the email I received this morning.
![image](https://user-images.githubusercontent.com/13984657/67877884-a2ff0980-faf7-11e9-880b-7a94bf2018cc.png)
![image](https://user-images.githubusercontent.com/13984657/67877953-c32ec880-faf7-11e9-9d74-80b0bd4095fd.png)

**Comment by jbolda** [comment]
Thanks for the issue. See #103 which should resolve this. @EvanHahn was on the ball, but I have had the time to cut a new version yet.

**Comment by jbolda** [comment]
Released!
https://github.com/jbolda/gatsby-source-airtable/releases/tag/2.0.10
