### ISSUE TITLE
Remote images from a string

### ISSUE THREAD

**Issue by fustkilas** [jbolda/gatsby-source-airtable#116]
Hello, my Airtable column contains URL strings to remote images, not attachments. So I am unable to use the example in `examples/recipes-with-photos`, since those are attachments.

My understanding is that gatsby-source-airtable uses gatsby-plugin-remote-images under the hood, so how can I set this up?

**Comment by jbolda** [comment]
👋 

It uses `gatsby-plugin-remote-images` to fetch images that are uploaded to Airtable. I don't think it is within the scope of this package to support this either. However, it might be accomplished in tandem with another plugin such as [`gatsby-plugin-remote-images`](https://github.com/graysonhicks/gatsby-plugin-remote-images).
