### ISSUE TITLE
Images 404 on production builds

### ISSUE THREAD

**Issue by dylanjha** [jbolda/gatsby-source-airtable#133]
When I run `gatsby clean && gatsby build && gatsby serve` I am getting 404s for some file attachments from Airtable.

* gatsby-source-airtable@^2.0.10
* gatsby-source-filesystem@^2.1.38

I have a page with 37 records that get pulled from airtable. The first 27 work and for the last 10 all the images end up 404ing. All the urls for the images look something like like this, the first 27 work and the last 10 get 404s:

```
static/b06e88f3b8a3788b42e8dc5b475f67b7/5d6e7/jacob-randall-square.jpg
```

I can't figure out why this is happening. The build logs don't show any obvious errors

I know this isn't a great bug-report with a proper reproducible case, but I don't have much else to go on, I was hoping someone who knows how the internals of the library works might be able to point me in the right direction for debugging.

Thanks 🙌

**Comment by dylanjha** [comment]
It sounds a lot like I was running into ratel limiting as described in #48 , but that looks like it was solved with the default concurrency of 5 requests

**Comment by jbolda** [comment]
I did that thing where you reply in your head, and never write the _real_ reply. :man_facepalming: 

Did you end up making any progress on this?

**Comment by dylanjha** [comment]
One up these upgrades solved the issue

`gatsby-plugin-sharp` from `2.0.21` to `2.3.9`
`gatsby` from `2.1.14` to `2.18.13`

I went through the changelogs and could not find the commit or an issue that I could trace it back to 🤷‍♂
