### ISSUE TITLE
Error at build time: tables is not defined for gatsby-source-airtable

### ISSUE THREAD

**Issue by jibe-b** [jbolda/gatsby-source-airtable#174]
Hi! I'm looking forward to displaying data collected through airtable but for the moment I get an error at build time.

I pass the api key in the command line `AIRTABLE_API_KEY=MyAPIkey gatsby develop` 

and here is the part of my `gatsby-config.js`that deals with the plugin:

```
  `gatsby-source-airtable`,
  {
    resolve: `gatsby-source-airtable`,
    options: {
      apiKey: process.env.AIRTABLE_API_KEY,
      concurrency: 5,
      tables: [
        {
          baseId: `appuuuieuieuieuieu`,
          tableName: `A magnificient table`,
        },
      ]
    }
  }
```

but I get the error message `tables is not defined for gatsby-source-airtable in gatsby-config.js`

Configuration: 
- Gatsby CLI version: 2.11.1
- Gatsby version: 2.20.7
- gatsby-source-airtable version: 6.13.4

Thanks a lot for your help!

**Comment by jbolda** [comment]
👋 

Is this copied directly out of your config? When you define a plugin in the config, you either use a string (if no options are needed) or you use an object with `` resolve: `gatsby-source-airtable` ``. It appears you may have used both in the snippet above. It processes these in order, and the first `gatsby-source-airtable` that it sees is the string version which does not have the options defined.

**Comment by jibe-b** [comment]
Hi @jbolda, first of all thank you for teaching me something I didn't know. I removed the line without the options defined.

Now the plugin throws an error but without any error message.

``` ERROR #11321  PLUGIN

"gatsby-source-airtable" threw an error while running the sourceNodes lifecycle:

  

warn The gatsby-source-airtable plugin has generated no Gatsby nodes. Do you need it?
```

What should I output in debug mode to help identifying where the plugin fails?

**Comment by jbolda** [comment]
It will throw errors as they surface. It doesn't have a special debug mode currently. I would recommend checking out the examples potentially.

In the config that you initially shared, using the `/` before the backtick is curious. Is that from copying and pasting?

**Comment by jibe-b** [comment]
Thank you for your answer. I added the backslashes after-copy-pasting because markdown was broken, but it was not needed.

The examples do not show much more. I will investigate.
