### ISSUE TITLE
queryName query

### ISSUE THREAD

**Issue by psmedia** [jbolda/gatsby-source-airtable#178]
Thanks for this wonderful plug-in, which is super useful! But I'm cracking my head trying to get the queryName option to run, so that I can have better distinguish data from two separate tables to run createPage across two different templates. My GraphQL continues to show only Airtable and allAirtable tables, even after running "gatsby clean", despite trying many variations.

Within Airtable or allAirtable tables I can see a new field,  "queryName": true,
But I am expecting to see new tables AirtableTable1 and AirtableTable2 here. Or do I have the wrong end of the stick? 
gatsby: 2.19.45
gatsby-source-airtable: 2.1.0
gatsby-cli: 2.11.0
```
{
      resolve: `gatsby-source-airtable`,
      options: {
        apiKey: `key************`, // may instead specify via env, see below
        concurrency: 5, // default, see using markdown and attachments for more information
        tables: [
          {
            baseId: `app***********`,
            tableName: `Table1`,
            queryName: true, // optionally default is false - makes all records in this table a separate node type, based on your tableView, or if not present, tableName, e.g. a table called "Fruit" would become "allAirtableFruit". Useful when pulling many airtables with similar structures or fields that have different types. See https://github.com/jbolda/gatsby-source-airtable/pull/52.
          },
          {
            baseId: `app**************`,
            tableName: `Table2`,
            queryName: true,
          }
        ]
      }
    }
```

**Comment by jbolda** [comment]
👋 Thanks for the kind words.

I think you are on the right track. `queryName` is expecting a string with the name of your choosing. For example in `Table1`, you may want `queryName: TableOne`. (I don't know how numbers in graphql work, maybe they are fine?)

If you have suggestions to make the documentation more clear, I always appreciate pull requests 😊 .

**Comment by jbolda** [comment]
That probably isn't intuitive that that error just gets fed through to the graphql query. I wonder if maybe we [wrap this in a try/catch block](https://github.com/jbolda/gatsby-source-airtable/blob/master/gatsby-node.js#L52-L60) and throw a `console.warn` so this is more obvious.
