### ISSUE TITLE
moving images to /public/ folder - publicURL is missing

### ISSUE THREAD

**Issue by brendanmc6** [jbolda/gatsby-source-airtable#18]
According to [the gatsby docs](https://www.gatsbyjs.org/docs/adding-images-fonts-files/), you can "_query the publicURL field of File nodes found in your data layer to trigger copying those files to the public directory and get URLs to them._"

localFiles does not seem to have this field. I'd appreciate any insight on how one might be able to query airtable image attachments and move them to /public/. The idea being that I could reference images directly in my markdown.

Maybe this needs to be done in a custom gatsby-node script (iterate over Photos array, idk), but I haven't been able to fund much useful documentation on how to approach this...

Let me know if you have any ideas, and how I can help.

**Comment by jbolda** [comment]
It appears that this has been fixed upstream. I see the publicURL on my site. Closing. Feel free to reopen if I am missing anything.
