### ISSUE TITLE
Fetch new content in development

### ISSUE THREAD

**Issue by adrienpoly** [jbolda/gatsby-source-airtable#21]
Hello 

Thanks for this excellent source plugin. While in development I was wondering if there is a way to force to refresh the GraphQl nodes when I update Airtable data.

Currently, the only solution I found was to kill my dev server and start it again. 

Maybe there is another trick?

Thanks

**Comment by brendanmc6** [comment]
@adrienpoly This is something I was looking into as well-- from what I understand, this would only be possible if Airtable themselves integrated Webhooks. Here is a popular feature request thread on precisely this topic:

https://community.airtable.com/t/webhooks-for-records/1966

As for avoiding a dev server restart but still doing things manually, it seems they have implemented an endpoint you can send a POST to, which triggers a data refresh. It isn't well documented, I've never tried it (`gatsby develop` is fast enough for me) but these two threads might help you get there:

https://github.com/gatsbyjs/gatsby/pull/3293
https://github.com/gatsbyjs/gatsby/pull/3054

**Comment by adrienpoly** [comment]
thanks a lot @brendanmc6 , it is very helpful
