### ISSUE TITLE
Obtain the Airtable column type 

### ISSUE THREAD

**Issue by Fernan-Ramos** [jbolda/gatsby-source-airtable#233]
I don't know if it's possible or not but I would like to know if there are any way to obtain the Airtable column type (`Long Text`, `Date`, `Email` etc) by each Table.
I need the column type after each node is created and also be able to make the query filtering by the type.

The purpose of this  that I want to translate the fields whose type are equal to  Airtable type `Long Text`.
Thanks!

**Comment by jbolda** [comment]
They didn't give access to that in the API last I looked, but they might now. If they do, happy to accept a PR.
