### ISSUE TITLE
Use gatsby-source-airtable in a command line tool?

### ISSUE THREAD

**Issue by edsu** [jbolda/gatsby-source-airtable#245]
Thanks for a very useful module! I was wondering if it might be possible to use gatsby-source-airtable in a stand alone command line tool that's part of my Gatsby project. This utility would run like `npm run fetch-data` and would query Airtable and persist the data locally to be queried using Gatsby's GraphQL abilities with CSV and JSON,

The reason why I ask is that I'd like to separate the build and develop runtime from Airtable, and have a representation of the data version controlled in my repository. But I still want the beauty of editing the data in Airtable.

Does this question make sense?

**Comment by jbolda** [comment]
👋

Most of what this plugin does it creating the nodes. If the intention is to create nodes through the filesystem, I imagine that it is probably easier to use the `airtable` library directly.

**Comment by edsu** [comment]
Yes, that makes a lot of sense. Does the airtable library offer the same clean graphql api that gatsby-source-airtable provides?

**Comment by edsu** [comment]
Automation truly sucks sometimes.

**Comment by jbolda** [comment]
Automatically is the only way to manage things sometimes with little time in a day unfortunately.

This package creates the nodes through Airtable. Removing this package and using the airtable package directly means you would need to create your own nodes. I would encourage you to check out the docs for airtable.js and node creation in gatsbyjs if that is a route you are interested in as that is out of the scope of this package.
