### ISSUE TITLE
Add support for `group by` in view

### ISSUE THREAD

**Issue by wassim** [jbolda/gatsby-source-airtable#254]
I have a view in Airtable with filter, sort and group by. I can query named view and results are filtered, sorted but not grouped like in Airtable! Is this normal?

```
{
    baseId: `***`,
    tableName: `posts`,
    tableView: `customView`,
    mapping: {
        image: `fileNode`,
    },
    tableLinks: [`categories`, `tags`],
    separateNodeType: true,
    queryName: `CustomPosts`,
}
```

```
{
  allAirtableCustomPosts() {
    nodes {
      id
      data {
        title
      }
    }
  }
}
```

**Comment by jbolda** [comment]
I haven't personally tried the group function and being able to query for it. I think the first step would be to check if airtable.js (and their API) has support for getting that information.
