### ISSUE TITLE
Consider making tableView parameter optional

### ISSUE THREAD

**Issue by ethagnawl** [jbolda/gatsby-source-airtable#27]
`view` looks to be an optional parameter when using the Airtable node library, so perhaps this library's `options.tables[N].tableView` parameter could also be made optional? I'm not using a view and, unless I provide an empty string, am met with the following error when building my application:

`Error: AssertionError [ERR_ASSERTION]: Airtable: invalid parameters for 'select': * the value for 'view' should be a string`

**Comment by jbolda** [comment]
Cheers, and thanks for the PR. Can't beat a bit of a DX improvement without downside.
