### ISSUE TITLE
Mapping a 'Long text' string field to 'text/markdown' results in it being parsed as 'fileNode' 2.1.1

### ISSUE THREAD

**Issue by roowilliams** [jbolda/gatsby-source-airtable#275]
`gatsby-source-airtable@2.1.1`

```
          {
            baseId: process.env.AIRTABLE_BASE_ID,
            tableName: `CONTENT`,
            separateNodeType: true,
            queryName: `SiteContent`,
            mapping: {
              Body: 'text/markdown',
              Images: 'fileNode',
            },
          },
```
As per title, when I leave the `Body` field without mapping the raw text is returned as a string including markdown formatting marks. When I specify mapping for that field as 'text/markdown' like above I end up with a `localFiles` node on `Body` (returns `null`). Have tried with and without mapping for `Images` to no avail.

**Comment by sangeet** [comment]
@roowilliams I had the exact same problem today. Were you able to figure out the reason for this bug? This is essentially not letting me map strings to markdown which is making me do the conversion on the UI side which sucks in comparison.
