### ISSUE TITLE
Filling all fields

### ISSUE THREAD

**Issue by eunjae-lee** [jbolda/gatsby-source-airtable#29]
When some fields are empty on a certain row, the api result from airtable doesn't include the field in that row.

![image](https://user-images.githubusercontent.com/499898/50545152-3dc35900-0c45-11e9-9396-3fc223478644.png)

```
{
  "records": [
    {
      "id": "recR4fJQsMlpWyy5A",
      "fields": {
        "Name": "John"
      },
      "createdTime": "2018-12-30T07:10:11.000Z"
    },
    {
      "id": "recoqit7jOBr8m6JK",
      "fields": {
        "Name": "Michael",
        "Notes": "Note1"
      },
      "createdTime": "2018-12-30T07:10:11.000Z"
    }
  ]
}
```

You can see "Notes" field is missing at the first row. Could we have a `fields` option?

```
    {
      resolve: 'gatsby-source-airtable',
      options: {
        apiKey: 'xxx',
        tables: [
          {
            baseId: 'xxx',
            tableName: 'xxx',
            tableView: 'xxx',
            fields: ['Name', 'Notes']
          },
        ],
      },
    }
```

When `fields` is specified, the result will always include all the fields with `null` as default value if none.
This is to prevent graphql query from failing. Refer to https://github.com/gatsbyjs/gatsby/issues/2392

What do you think?

**Comment by eunjae-lee** [comment]
Firstly, it's Airtable's decision not to fill all the fields when their values are null and it's pretty common situation. So we cannot do anything about it.
Secondly, as soon(?) as gatsby fix those issue, this fix will be useless.

So as you suggest, `defaultValues` sounds a good way to cover this problem and also provides something useful to other users as well. And actually that's a better fix than my previous suggestion because all fields might have different default values.

**Comment by jbolda** [comment]
>Firstly, it's Airtable's decision not to fill all the fields when their values are null and it's pretty common situation. So we cannot do anything about it.

Agreed as well. (I didn't make that clear in my previous comment.)

Sounds perfect to me. Would you be available to work on a PR for this?

**Comment by eunjae-lee** [comment]
Sure. I'll try to work on it in a couple of days. Ah, by the way, happy new year 🎉

**Comment by jbolda** [comment]
Great! Thanks again for the help, and happy new year to you as well!
