### ISSUE TITLE
Deep Linking only shows up strings?

### ISSUE THREAD

**Issue by fustkilas** [jbolda/gatsby-source-airtable#38]
hello, I have two tables, 
- "Shows" with a list of exhibitions 
- "People" with a list of people

the "Shows" table has a field linked to the "People" table so I can pull in multiple people associated with the exhibitions.

now my gatsby-config looks like this:

```javascript
    {
      resolve: `gatsby-source-airtable`,
      options: {
        apiKey: process.env.GATSBY_AIRTABLE_APIKEY, 
        tables: [
          {
            baseId: process.env.GATSBY_AIRTABLE_BASEID,
            tableName: `Shows`,
            tableView: `Gallery`,
            tableLinks: [`Entities`, `People`],
            mapping: { Images: `fileNode` }
          },
          {
            baseId: process.env.GATSBY_AIRTABLE_BASEID,
            tableName: `People`,
            tableView: `Main`,
            tableLinks: [`Shows`]
          }
        ]
      }
    }
```

Now if I do

```
{
  allAirtable(filter:{table:{eq:"Shows"}}) {
    edges {
      node {
        data {
          Artists
        }
      }
    }
  }
}
```

I get a array of Artist ids as strings.

But this isn't what I need; I need them 'denormalised' I guess.

How to do so?

**Comment by jbolda** [comment]
It sounds like your field name is `Artists` which is what you should refer to in your `tableLinks` as noted in [this part of the readme](https://github.com/jbolda/gatsby-source-airtable#deep-linking-across-tables). If the readme is unclear, I would love any revisions to make it more understandable. Otherwise, let me know if my assumption is incorrect!

**Comment by fustkilas** [comment]
Indeed, the readme is thorough. It took me a couple of refreshes of my `gatsby develop` step for it to work.
Thanks J, I will close this up.
