### ISSUE TITLE
Mapping Confusion

### ISSUE THREAD

**Issue by xavdid** [jbolda/gatsby-source-airtable#39]
Hi there!

First off - this is an awesome project. It's worked basically flawlessly  and I've been really impressed. So, kudos.

I wanted to reach out about a bit of confusion I had around the `mapping` feature. I've got a formula field (`isHidden`) that does an `OR` on two other fields and produces either `0` or `1`. This pulls into graphql just fine. I read the following:

> Optionally, you may provide a "mapping". This will alert the plugin that column names you specify are of a specific, non-string format of your choosing

and took that to mean I could transform the data to a different data type. In my case, I could coerce my formula output into a `boolean`. There's a very good chance I'm misunderstanding what that feature is supposed to do.

Expected:

```js
{ isHidden: 1 }
       + 
{ mapping: { isHidden: 'Boolean' } }

// becomes

{ isHidden: true }
```

Actual:
```js
{ isHidden: 1 } 
       + 
{ mapping: { isHidden: 'Boolean' } }

// becomes

{
  isHidden: {
    id: "abc-123",
    raw: 1
  }
}
```

Anyway, feel free to let me know if I'm doing something foolish. This is mostly for testing anyway, so no big priority.

**Comment by jbolda** [comment]
Glad everything has gone relatively smoothly for you!

Yea, I can understand how you reading it. Happy to take a PR if you have a better wording. We don't actually coerce any data, but rather you are just clueing Gatsby core into what kind of data that field contains. If you do not give it a mapping, Gatsby will infer (see educated guess) what the data is and create nodes to suit. Sometimes this is fine, other times not. You can read more about the process [here](https://www.gatsbyjs.org/docs/schema-gql-type/).

If you do want to coerce the data, I would generally recommend adding a field. The core docs have a [paragraph about it](https://www.gatsbyjs.org/docs/node-creation/#changing-a-nodes-fields), but if you need a little bit more direction, I am sure that I have an example somewhere. The more involved / advanced use case would be to create entirely new nodes which is what the transformer type plugins typically do.

**Comment by xavdid** [comment]
I don't actually need the field. the int -> bool mapping was mostly a convenience thing if it was possible. 

I'm afraid i'm still not super clear on what the mapping is for, so I can't suggest a better wording. I'm still pretty new to gatsby though, so there's a lot I haven't quite grasped yet. No worries!
