### ISSUE TITLE
ENV var naming scheme leaks into public build

### ISSUE THREAD

**Issue by coreyward** [jbolda/gatsby-source-airtable#40]
[ENV vars prefixed with `GATSBY_` are sent to the client.](https://www.gatsbyjs.org/docs/environment-variables/#defining-environment-variables)

> OS Env Vars which are prefixed with GATSBY_ will become available in browser JavaScript.

If you don't want someone having access to the API key that you're putting in `gatsby-config.js`, you almost certainly don't want to be sending it to the client/browser.

**Comment by jbolda** [comment]
Well, that certainly is an oversight. I missed that that feature was added. 😅 Fortunately, it will only send it client side if you reference it client side (via `process.env.GATSBY_AIRTABLE_API_KEY`). This plugin doesn't do that, but it is certainly a potential footgun for the user to do. Thanks for bringing this up; we should update the documentation here and deprecate use of `GATSBY_AIRTABLE_API_KEY`. Would you be available to make a PR for this?

**Comment by coreyward** [comment]
@jbolda I don't use the plugin, just happened to notice while doing some cursory investigating, so I'd prefer not to be responsible for the change.

**Comment by jamessimone** [comment]
We did not end up deprecating the allowance for the "magic" GATSBY_AIRTABLE_API_KEY environment variable with the changes referenced above, but if the apiKey is not explicitly set in the gatsby-source-airtable config, a warning is now printed to the console concerning the future deprecation of GATSBY_AIRTABLE_API_KEY.

**Comment by jbolda** [comment]
I'm going to go ahead and close this as we have started the plan the deprecate already. Thanks for bringing it to our attention.
