### ISSUE TITLE
duplicate field names across tables?

### ISSUE THREAD

**Issue by fustkilas** [jbolda/gatsby-source-airtable#42]
hello, this might be due to my misunderstanding how gatsby-source-airtable queries using GraphQL, but are duplicate field names across tables not allowed/deprecated?

**Comment by jbolda** [comment]
It is allowed, but currently, they need to be the same type of data or you run into issues. See #25 and #41 for more information. (There is a solution, but no one has had to time to add it yet.)

**Comment by jbolda** [comment]
I am going to close this issue in favor of tracking in the other linked issues.
