### ISSUE TITLE
Getting error "Cannot destructure property createNode of undefined or null"

### ISSUE THREAD

**Issue by robations** [jbolda/gatsby-source-airtable#43]
I was trying to follow the tutorial [here](https://blog.airtable.com/build-your-own-custom-blog-cms-with-airtable-and-gatsbyjs/) but after adding the plugin config for `gatsby-source-airtable` I get the following error:

```
$ gatsby develop
success delete html and css files from previous builds — 0.014 s
success open and validate gatsby-config — 0.004 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success copy gatsby files — 0.009 s
success onPreBootstrap — 0.435 s
error Plugin gatsby-source-airtable returned an error

  TypeError: Cannot destructure property `createNode` of 'undefined' or 'null'.
  
  - gatsby-node.js:10 Object.exports.sourceNodes
    [airtable-test]/[gatsby-source-airtable]/gatsby-node.js:10:43
  
  - api-runner-node.js:110 runAPI
    [airtable-test]/[gatsby]/dist/utils/api-runner-node.js:110:36
...
```

### Environment
- OS: MacOS 10.14.3
- node: 10.15.1
- gatsby-cli: 2.4.12

### To reproduce:

```
gatsby new airtable-test https://github.com/davad/gatsby-hampton-theme
cd airtable-test
# this actually fails in my environment due to libvips vs sharp
# it's necessary to add a key to package.json e.g. resolutions.sharp = "0.21.3"
yarn # repeat install due to previous failure
# edit gatsby-config.js to add `gatsby-source-airtable` and one table as described in README (tutorial looks out of date)
gatsby develop
# fails with error as above
```

I'm fairly new to gatsby, am I missing something?

**Comment by robations** [comment]
I suspect this is because this "theme" is actually a starter package that seeds the whole project with gatsby v1, even though gatsby-cli is v2.x. Fairly confusing.

**Comment by santiesteban** [comment]
@robations Did you figure out how to fix it?

**Comment by robations** [comment]
@santiesteban I don't remember exactly, but I took a quick look at the project/experiment.

I think I changed the `gatsby` spec in `package.json` to version 2, and migrated the gatsby config. There's a guide [here](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/) though I don't remember doing half this stuff.

**Comment by jbolda** [comment]
Yep, that blog post is rather out of date at this point.

**Comment by santiesteban** [comment]
@robations Thank you. I gave it a shot but that guide was a little beyond me.
