### ISSUE TITLE
#<Promise> is not an iterator

### ISSUE THREAD

**Issue by amlcodes** [jbolda/gatsby-source-airtable#44]
gatsby new airtableExample

yarn add gatsby-source-airtable

add in gatsby.config airtable data.

run gatsby develop or build, will get #<Promise> is not an iterator. losing my mind

**Comment by jonesbp** [comment]
I am experiencing the same problem. Under `gatsby develop` I actually get useful functionality with what I imagine to be a moderately complicated use (querying two layers deep in linked tables, etc.) in spite of the error. `gatsby build` hits the error and exits, of course.

I can also recreate using the barebones steps outlined in the original post.

**Comment by jlengstorf** [comment]
I’m seeing this, too. Haven't had a chance to dig into it, but I need to publish something shortly, so I'll probably be back with more insights. 😄

**Comment by jbolda** [comment]
Something changed in the core that is breaking things. We are hitting the `catch` [here](https://github.com/jbolda/gatsby-source-airtable/blob/master/gatsby-node.js#L284-L289) in our CI builds. Looks like it may be related to `createRemoteFileNode`. I don't have the time right now to dig in further though.

**Comment by jbolda** [comment]
One of the CI build failures if anyone needs a reference: https://travis-ci.com/jbolda/gatsby-source-airtable/jobs/187304670

**Comment by pieh** [comment]
This https://github.com/gatsbyjs/gatsby/pull/12691 seems to cause this problem. Need to investigate it (potentially revert), but for a workaround - you can add
```
global.Promise = require(`bluebird`)
```
In your site `gatsby-node.js` file

**Comment by jlengstorf** [comment]
Okay — thanks to @pieh's help, I have a workaround for this.

We removed the global Bluebird `Promise` polyfill in https://github.com/gatsbyjs/gatsby/pull/12691. It appears that this plugin was relying on that.

To work around it, add this to your `gatsby-node.js`:

```js
global.Promise = require('bluebird');
```

We're looking into a better solution here — one working theory is that this plugin needs to be transpiled. I'll report back with what we find.

**Comment by jlengstorf** [comment]
Ha. As usual, @pieh is one step ahead of me. 😂
