### ISSUE TITLE
Pulling table descriptions

### ISSUE THREAD

**Issue by robinmetral** [jbolda/gatsby-source-airtable#55]
Hi and thank you for the amazing plugin!

I'm wondering if there's a way to query table descriptions from my base. That's the text that appears when you hover the small :information_source: on a table (if the description was provided):

![Screenshot_2019-06-26 Green List Berlin - Airtable](https://user-images.githubusercontent.com/35560568/60178621-42478380-981c-11e9-9a79-5ad09d99970d.png)

Forgive me if this is already documented, but I couldn't find any mention to it anywhere.

**Comment by jbolda** [comment]
I don't think that is something we have supported. Are you interested in submitting a PR?

**Comment by robinmetral** [comment]
After a quick research, I'm actually not sure it's evn possible to pull this data from the Airtable API.

I've messaged support and will post their answer here.

**Comment by robinmetral** [comment]
> A metadata API is not currently supported in Airtable to view/modify users, workspaces, or the base structure (fields and tables).  This includes the table description.

This closes the issue. To link descriptive texts to a table, we could consider having a separate table, or sourcing from a local yaml file, for example.
