### ISSUE TITLE
Filenodes being cut off on automated static builds on host(s)

### ISSUE THREAD

**Issue by brohlson** [jbolda/gatsby-source-airtable#56]
I have a Gatsby site that sources around 130 images from 4 tables.  Starting just within the last few hours, the sourcing process is being cut short by my static host, Netlify, and just was able to recreate on Render.com.  

This particular part of the build script completes fine with a local build at around 22 seconds
```
fetch all Airtable rows from 4 tables: 966.588ms
success source and transform nodes - 22.539 s
```

On Netlify, it seems that the process is getting truncated, and I'm afraid I don't have any version bumps or new plugin additions to test against. 
```
9:00:25 PM: fetch all Airtable rows from 4 tables: 622.436ms
9:00:33 PM: success source and transform nodes — 9.333 s
```

It's grabbing the first 15-20 images in the proper order, so I'm guessing maybe some sort of API pagination issue is causing static hosts build images to think the sourcing is completed before it's meant to be.  

My deps:
```
    "babel-plugin-styled-components": "^1.8.0",
    "gatsby": "^2.5.0",
    "gatsby-image": "^2.1.0",
    "gatsby-plugin-google-analytics": "^2.0.9",
    "gatsby-plugin-layout": "^1.1.0",
    "gatsby-plugin-manifest": "^2.0.5",
    "gatsby-plugin-nprogress": "^2.0.7",
    "gatsby-plugin-offline": "^2.0.11",
    "gatsby-plugin-react-helmet": "^3.0.0",
    "gatsby-plugin-sharp": "^2.0.7",
    "gatsby-plugin-sitemap": "^2.0.4",
    "gatsby-plugin-styled-components": "^3.0.3",
    "gatsby-source-airtable": "^2.0.8",
    "gatsby-source-filesystem": "^2.0.36",
    "gatsby-transformer-sharp": "^2.1.4",
    "nuka-carousel": "^4.4.3",
    "path": "^0.12.7",
    "react": "^16.5.1",
    "react-dom": "^16.5.1",
    "react-helmet": "^5.2.0",
    "styled-components": "^4.1.1",
    "underscore": "^1.9.1"
```

I tried updating the `concurrency` value from 1-5, 10, 20, 50, 100.  No dice.  

Curious if this has happened to anyone else today or maybe I've hit some sort of temporary rate limiting. 

Thanks!

**Comment by brohlson** [comment]
So after a few hours of tinkering, I found that this is actually an issue somewhere close to the metal related to `gatsby-transformer-sharp` and `gatsby-plugin-sharp` when using large sizes or quantity of media. 

Here's a link to the comment with some tips that have my builds succeeding intermittently:
https://github.com/gatsbyjs/gatsby/issues/6291#issuecomment-505097465

I'll leave this issue open and confirm if/when a patch is made to these packages that resolves it.

**Comment by jbolda** [comment]
Thanks for digging in and following up!

**Comment by brohlson** [comment]
Seems like this issue is being resolved by the `sharp` plugins respecting GATSBY_CPU_COUNT, my builds are resuming with more regularity.  Gonna close this out but I imagine the threads linked above will remain open as long as this issue lives.
