### ISSUE TITLE
RegeneratorRuntime is not defined

### ISSUE THREAD

**Issue by devrchancay** [jbolda/gatsby-source-airtable#6]
Hello I just opened an issue in the gatsbyjs repository if you can help me please.

https://github.com/gatsbyjs/gatsby/issues/8175

**Comment by devrchancay** [comment]
Finally I could solve adding this line to the start of gatsby-config.js
```javascript
require('regenerator-runtime/runtime')
```
I still can not find how to support ES6-7-8 to gatsby, probably looking in the wrong place.

**Comment by jbolda** [comment]
Would you be able to share any more information? Versions of anything related would be a start. I believe this is on `0.0.6`?

**Comment by jbolda** [comment]
Also any frontend code like es6+ would be handled by Gatsby, not this plugin.
