### ISSUE TITLE
- Unknown field 'airtable' on type 'Query'.  File: src/templates/search-post.js

### ISSUE THREAD

**Issue by ethaneisenhard** [jbolda/gatsby-source-airtable#60]
I am trying to make a simple algolia and airtable search engine.

I am able to query the airtable DB into the algolia API.

My issue is that when i want to create a page for each of the results the airtable query does not work. 

However, the query works in the gatsby.config but no where else in the repo.

I have the correct plugins installed (i am using NPM & i have tried Yarn) and I have the correct API keys installed because i can see it works on the dev branch and in algolia. 

What's strange is that in the graqphQL explorer airtable is not an option and returns an error. But then how does it work getting into Algolia in the gatsby.config file?? I have used a ton of example repos including this one. 

Wonder if anyone has seen this before

the master repo
https://github.com/ethaneisenhard/gatsby-algolia-airtable2

the dev working repo (just the airtable to algolia connection)
https://github.com/ethaneisenhard/gatsby-algolia-airtable2/tree/dev

the issue NOT working repo (airtable to algolia connection plus the createPage node attempt)
https://github.com/ethaneisenhard/gatsby-algolia-airtable2/tree/issue

the issue repo is using a different Base in my Airtable API than the working Dev. I copied the issue base one from the recipe example in this repo.

https://github.com/jbolda/gatsby-source-airtable/tree/master/examples/recipes-with-photos

**Comment by jbolda** [comment]
What is the error that you see in the explorer?

If you are looking to `createPage` from Airtable, I would expect to see that in your [`gatsby-node.js`](https://github.com/ethaneisenhard/gatsby-algolia-airtable2/blob/master/gatsby-node.js#L9-L27).

**Comment by ethaneisenhard** [comment]
@jbolda Thanks for responding

Yes! you are defiantly correct about that, I had gone through and tried that for some reason i did not push those changes 

The error I am getting 

Import it instead like:  import { graphql } from 'gatsby' in file:

 ERROR #85907  GRAPHQL

There was an error in your GraphQL query:

- Unknown field 'airtable' on type 'Query'.

**Comment by ethaneisenhard** [comment]
https://github.com/ethaneisenhard/gatsby-algolia-airtable2/tree/issue

I have updated the repo to match your recipe example

The issue is the Gatsby wont accept airtable as a query!

**Comment by jbolda** [comment]
It appears to me that you have something misconfigured with your environment variables. I get a lot of errors due to algolia and markdownRemark, but I am still able to get airtable nodes by using my own API key (as you have made a direct copy of the example, it "just works").
