### ISSUE TITLE
Update Airtable API Client to fix LoDash dependency

### ISSUE THREAD

**Issue by karllhughes** [jbolda/gatsby-source-airtable#62]
The version of the Airtable API client currently being used uses an old version of lodash which has a known security vulnerability. We should upgrade this repo to version [0.7.0](https://github.com/Airtable/airtable.js/releases/tag/v0.7.0) or greater to fix this.

Happy to make a PR updating the NPM package, but as I haven't contributed before, I wanted to drop an issue first and make sure it wasn't already a known issue. Thanks!

**Comment by jamessimone** [comment]
@karllhughes I submitted a PR, thanks for raising the issue!

**Comment by jbolda** [comment]
This plugin only runs on build with no client-side interaction. To my knowledge, the vulnerability does not affect us, but I am happy to update just to avoid any questions.
